name: Altfins Scraper Cron

on:
  schedule:
    # Run every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allow manual triggering from GitHub UI

jobs:
  scrape-data:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip' # Cache pip dependencies to speed up runs

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Scraper
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
          ALTFINS_URL_LOGIN: ${{ secrets.ALTFINS_URL_LOGIN }}
          ALTFINS_URL_ANALYSIS: ${{ secrets.ALTFINS_URL_ANALYSIS }}
          ALTFINS_ACCOUNT: ${{ secrets.ALTFINS_ACCOUNT }}
          ALTFINS_PASSWORD: ${{ secrets.ALTFINS_PASSWORD }}
        run: python scraper.py
